### ISSUE TITLE
No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by randomprimate** [damjack/spree_banner#12]
I'm getting the following error when running the rails generator.  I'm using Spree 2.4 which I'm guessing is the main issue here but I'd like to know how to go about this problem.

```
7ddf32e17a6ac5:crops_banners hades$ rails g spree_banner:install
      append  app/assets/javascripts/admin/all.js
/Users/username/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:98:in `binread': No such file or directory @ rb_sysopen - /Users/username/RubymineProjects/spree_banners_app/app/assets/javascripts/admin/all.js (Errno::ENOENT)
    from /Users/username/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:98:in `replace!'
    from /Users/username/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:59:in `invoke!'
    from /Users/username/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
    from /Users/username/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:30:in `insert_into_file'
    from /Users/username/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:180:in `append_to_file'
    from /Users/username/.rvm/gems/ruby-2.1.5/bundler/gems/spree_banner-b14044b13e12/lib/generators/spree_banner/install/install_generator.rb:6:in `add_javascripts'
    from /Users/username/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/username/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/username/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
    from /Users/username/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
    from /Users/username/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
    from /Users/username/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
    from /Users/username/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
    from /Users/username/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/username/.rvm/gems/ruby-2.1.5/gems/railties-4.1.8/lib/rails/generators.rb:157:in `invoke'
    from /Users/username/.rvm/gems/ruby-2.1.5/gems/railties-4.1.8/lib/rails/commands/generate.rb:11:in `<top (required)>'
    from /Users/username/.rvm/gems/ruby-2.1.5/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
    from /Users/username/.rvm/gems/ruby-2.1.5/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
    from /Users/username/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `block in require'
    from /Users/username/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
    from /Users/username/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
    from /Users/username/.rvm/gems/ruby-2.1.5/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:135:in `generate_or_destroy'
    from /Users/username/.rvm/gems/ruby-2.1.5/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:51:in `generate'
    from /Users/username/.rvm/gems/ruby-2.1.5/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
    from /Users/username/.rvm/gems/ruby-2.1.5/gems/railties-4.1.8/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

**Comment by LightEmitting** [comment]
same issue.
